"""Cache Scanner Service: Discovers safe system, package manager, and framework caches."""

import logging
from collections.abc import Callable
from pathlib import Path

from app.constants import CleanupCategory, SafetyLevel
from app.paths import get_local_appdata, get_system_temp_dir, get_user_home, get_user_temp_dir
from models.cleanup_item import CleanupCandidate
from services.recycle_bin_service import RecycleBinService
from services.safety_engine import SafetyEngine
from utils.filesystem import get_dir_size_and_count

logger = logging.getLogger("PcClean.CacheService")


class CacheService:
    def __init__(self, safety_engine: SafetyEngine | None = None):
        self.safety_engine = safety_engine or SafetyEngine()

    def scan_all_caches(
        self, is_cancelled: Callable[[], bool] | None = None, progress_callback: Callable[[str], None] | None = None
    ) -> list[CleanupCandidate]:
        """Scan all known safe cache locations."""
        candidates: list[CleanupCandidate] = []
        user_home = get_user_home()
        local_appdata = get_local_appdata()

        targets = [
            {
                "id": "user_temp",
                "name": "User Temp Files",
                "category": CleanupCategory.USER_TEMP,
                "path": get_user_temp_dir(),
                "safety": SafetyLevel.SAFE,
                "description": "User temporary files created by applications. Locked files are safely skipped.",
                "explanation": "Temporary files generated by running programs. Completely safe to clean; active files in use are skipped automatically.",
            },
            {
                "id": "system_temp",
                "name": "Windows Temp Files",
                "category": CleanupCategory.WINDOWS_TEMP,
                "path": get_system_temp_dir(),
                "safety": SafetyLevel.SAFE,
                "description": "Windows system-level temporary directory. Requires administrator rights.",
                "explanation": "Operating system temporary cache files. Requires administrator elevation to clean.",
            },
            {
                "id": "npm_cache",
                "name": "npm Package Cache",
                "category": CleanupCategory.NODE_CACHE,
                "path": local_appdata / "npm-cache",
                "safety": SafetyLevel.SAFE,
                "description": "npm package tarball cache.",
                "explanation": "Downloaded package archives. Packages can be re-downloaded seamlessly when running 'npm install'.",
            },
            {
                "id": "pnpm_cache",
                "name": "pnpm Store",
                "category": CleanupCategory.NODE_CACHE,
                "path": local_appdata / "pnpm" / "store",
                "safety": SafetyLevel.SAFE,
                "description": "pnpm content-addressable package storage.",
                "explanation": "pnpm dependency cache. Artifacts are automatically redownloaded when needed.",
            },
            {
                "id": "yarn_cache",
                "name": "Yarn Cache",
                "category": CleanupCategory.NODE_CACHE,
                "path": local_appdata / "Yarn" / "Cache",
                "safety": SafetyLevel.SAFE,
                "description": "Yarn package manager cache.",
                "explanation": "Offline package cache for Yarn. Packages will be redownloaded on next yarn install.",
            },
            {
                "id": "bun_cache",
                "name": "Bun Cache",
                "category": CleanupCategory.NODE_CACHE,
                "path": user_home / ".bun" / "install" / "cache",
                "safety": SafetyLevel.SAFE,
                "description": "Bun package manager cache.",
                "explanation": "Cached package downloads for the Bun JavaScript runtime.",
            },
            {
                "id": "pip_cache",
                "name": "pip Cache",
                "category": CleanupCategory.PYTHON_CACHE,
                "path": local_appdata / "pip" / "cache",
                "safety": SafetyLevel.SAFE,
                "description": "Python pip package and wheel cache.",
                "explanation": "Cached Python wheels and HTTP responses. Pip downloads them on demand.",
            },
            {
                "id": "uv_cache",
                "name": "uv Cache",
                "category": CleanupCategory.PYTHON_CACHE,
                "path": local_appdata / "uv" / "cache",
                "safety": SafetyLevel.SAFE,
                "description": "uv ultra-fast package installer cache.",
                "explanation": "Cached wheels and git checkouts managed by Astral uv.",
            },
            {
                "id": "playwright_cache",
                "name": "Playwright Browser Binaries",
                "category": CleanupCategory.NODE_CACHE,
                "path": local_appdata / "ms-playwright",
                "safety": SafetyLevel.SAFE_REDOWNLOAD,
                "description": "Playwright headless Chromium, Firefox, WebKit builds.",
                "explanation": "Playwright browser binaries. Re-downloaded via 'npx playwright install' at any time.",
            },
            {
                "id": "gradle_cache",
                "name": "Gradle Artifact Caches",
                "category": CleanupCategory.GRADLE_CACHE,
                "path": user_home / ".gradle" / "caches",
                "safety": SafetyLevel.SAFE_REDOWNLOAD,
                "description": "Gradle dependency and wrapper cache.",
                "explanation": "Cached Java/Kotlin jar dependencies. Downloaded automatically during Gradle builds.",
            },
            {
                "id": "crash_dumps",
                "name": "Windows Crash Dumps",
                "category": CleanupCategory.LOGS_AND_CRASH,
                "path": local_appdata / "CrashDumps",
                "safety": SafetyLevel.SAFE,
                "description": "Application crash dump minidumps (.dmp).",
                "explanation": "Generated when applications terminate unexpectedly. Safe to clean unless debugging.",
            },
            {
                "id": "pub_cache",
                "name": "Flutter / Pub Cache",
                "category": CleanupCategory.FLUTTER_CACHE,
                "path": local_appdata / "Pub" / "Cache",
                "safety": SafetyLevel.SAFE_REDOWNLOAD,
                "description": "Dart & Flutter pub package cache.",
                "explanation": "Cached Dart packages. Downloaded automatically via 'flutter pub get'.",
            },
        ]

        # Scan folder targets
        for t in targets:
            if is_cancelled and is_cancelled():
                break
            p = t["path"]
            if progress_callback:
                progress_callback(f"Checking {t['name']}...")
            if p.exists():
                size, files, _ = get_dir_size_and_count(p, is_cancelled=is_cancelled)
                if size > 0:
                    safety_res = self.safety_engine.evaluate_path(p)
                    candidates.append(
                        CleanupCandidate(
                            id=t["id"],
                            name=t["name"],
                            description=t["description"],
                            path=p,
                            category=t["category"],
                            size=size,
                            files_count=files,
                            safety_level=t["safety"],
                            reason=safety_res.reason,
                            is_selected=(t["safety"] == SafetyLevel.SAFE),
                            is_protected=safety_res.is_protected,
                            can_recycle=True,
                            explanation=t["explanation"],
                        )
                    )

        # Check Recycle Bin
        if not (is_cancelled and is_cancelled()):
            rb_size, rb_count = RecycleBinService.get_info()
            if rb_size > 0 or rb_count > 0:
                candidates.append(
                    CleanupCandidate(
                        id="recycle_bin",
                        name="Windows Recycle Bin",
                        description="Files deleted by the user awaiting permanent purge.",
                        path=Path("C:\\$Recycle.Bin"),
                        category=CleanupCategory.RECYCLE_BIN,
                        size=rb_size,
                        files_count=rb_count,
                        safety_level=SafetyLevel.SAFE,
                        reason="Recycle Bin contains items previously deleted by user.",
                        is_selected=True,
                        is_protected=False,
                        can_recycle=False,
                        explanation="Permanently clears items currently stored in the Windows Recycle Bin.",
                    )
                )

        return candidates
